api = "0.4"

[buildpack]
  id = "paketo-buildpacks/nginx"
  name = "Paketo Nginx Server Buildpack"
  homepage = "https://github.com/paketo-buildpacks/nginx"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "bin/configure", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    nginx = "1.21.*"

  [[metadata.dependencies]]
    id = "nginx"
    name = "Nginx Server"
    sha256 = "801bde5e490b3341e5780e77a0736e904e89dc9bf3000077b2ade4c3834d443b"
    source = "http://nginx.org/download/nginx-1.20.0.tar.gz"
    source_sha256 = "54ef91ec8ebcaa486c640c09c92d832eaeaff149b10ee52ef140f407b1b04d1c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.20.0_linux_x64_cflinuxfs3_801bde5e.tgz"
    version = "1.20.0"

  [[metadata.dependencies]]
    id = "nginx"
    name = "Nginx Server"
    sha256 = "1758f1a31daad32d5a648739ea72e9190c482ae54ee9502a527a2a7f3ee8a70a"
    source = "http://nginx.org/download/nginx-1.20.1.tar.gz"
    source_sha256 = "e462e11533d5c30baa05df7652160ff5979591d291736cfa5edb9fd2edb48c49"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.20.1_linux_x64_cflinuxfs3_1758f1a3.tgz"
    version = "1.20.1"

  [[metadata.dependencies]]
    deprecation_date = "2022-05-25T00:00:00Z"
    id = "nginx"
    name = "Nginx Server"
    sha256 = "49a96d33d67d76faed028aaca6b9ba74c2120127285faecdf7943d5f66ce1b0b"
    source = "http://nginx.org/download/nginx-1.21.0.tar.gz"
    source_sha256 = "fe192a4bac2bd3a769e8695cb9fe14a00e57eaceb919095347a83b5b2afc0771"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.21.0_linux_x64_cflinuxfs3_49a96d33.tgz"
    version = "1.21.0"

  [[metadata.dependencies]]
    deprecation_date = "2022-05-25T00:00:00Z"
    id = "nginx"
    name = "Nginx Server"
    sha256 = "f0918d6bfafa1259d72f4d798f916f134602efd5534a04f115388a9a6c3b5635"
    source = "http://nginx.org/download/nginx-1.21.1.tar.gz"
    source_sha256 = "68ba0311342115163a0354cad34f90c05a7e8bf689dc498abf07899eda155560"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.21.1_linux_x64_cflinuxfs3_f0918d6b.tgz"
    version = "1.21.1"

  [[metadata.dependency_deprecation_dates]]
    date = "2022-05-25T00:00:00Z"
    link = "https://nginx.org/"
    name = "nginx"
    version_line = "1.21.x"

  [[metadata.dependency_deprecation_dates]]
    date = "2022-05-25T00:00:00Z"
    link = "https://nginx.org/"
    name = "nginx"
    version_line = "1.20.x"
  [metadata.version-lines]
    mainline = "1.21.*"
    stable = "1.20.*"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
