api = "0.2"

[buildpack]
  id = "paketo-buildpacks/nginx"
  name = "Nginx Server Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "bin/configure", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    nginx = "1.17.*"

  [[metadata.dependencies]]
    id = "nginx"
    name = "Nginx Server"
    sha256 = "87dcb4a7cdd46cb0cb8843a0159bfdd39083c5dc18acc944e35dc501f07d5a90"
    source = "http://nginx.org/download/nginx-1.16.0.tar.gz"
    source_sha256 = "4fd376bad78797e7f18094a00f0f1088259326436b537eb5af69b01be2ca1345"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx-1.16.0-linux-x64-cflinuxfs3-87dcb4a7.tgz"
    version = "1.16.0"

  [[metadata.dependencies]]
    id = "nginx"
    name = "Nginx Server"
    sha256 = "89a5c316a20cd2a4f44699cce0ba9962726b9795f8b3886f4c3e28cb3151b53d"
    source = "http://nginx.org/download/nginx-1.16.1.tar.gz"
    source_sha256 = "f11c2a6dd1d3515736f0324857957db2de98be862461b5a542a3ac6188dbe32b"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx-1.16.1-linux-x64-cflinuxfs3-89a5c316.tgz"
    version = "1.16.1"

  [[metadata.dependencies]]
    id = "nginx"
    name = "Nginx Server"
    sha256 = "9efdb55180b30ee47b9fb9d91d8c80ce4150ae551785954730cd7831c82142ea"
    source = "http://nginx.org/download/nginx-1.17.9.tar.gz"
    source_sha256 = "7dd65d405c753c41b7fdab9415cfb4bdbaf093ec6d9f7432072d52cb7bcbb689"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx-1.17.9-linux-x64-cflinuxfs3-9efdb551.tgz"
    version = "1.17.9"

  [[metadata.dependencies]]
    deprecation_date = "2020-05-01T00:00:00Z"
    id = "nginx"
    name = "Nginx Server"
    sha256 = "a35b89e953163e7ce85cb9cad1a921ee4385a5aa6f6971288d0a6bff4f23dad5"
    source = "http://nginx.org/download/nginx-1.17.10.tar.gz"
    source_sha256 = "a9aa73f19c352a6b166d78e2a664bb3ef1295bbe6d3cc5aa7404bd4664ab4b83"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.17.10_linux_x64_cflinuxfs3_a35b89e9.tgz"
    version = "1.17.10"

  [[metadata.dependencies]]
    deprecation_date = "2021-05-01T00:00:00Z"
    id = "nginx"
    name = "Nginx Server"
    sha256 = "10435f5f0c512e0744e53dce7553f7b1ac7cd7377e244d2d7ce83ff251c9ec7c"
    source = "http://nginx.org/download/nginx-1.18.0.tar.gz"
    source_sha256 = "4c373e7ab5bf91d34a4f11a0c9496561061ba5eee6020db272a17a7228d35f99"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.18.0_linux_x64_cflinuxfs3_10435f5f.tgz"
    version = "1.18.0"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-04-01T00:00:00Z
    link = "https://nginx.org/"
    name = "nginx"
    version_line = "1.16.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-05-01T00:00:00Z
    link = "https://nginx.org/"
    name = "nginx"
    version_line = "1.17.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-05-01T00:00:00Z
    link = "https://nginx.org/"
    name = "nginx"
    version_line = "1.18.x"
  [metadata.version-lines]
    mainline = "1.17.*"
    stable = "1.16.*"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
