api = "0.2"

[buildpack]
  id = "paketo-buildpacks/nginx"
  name = "Paketo Nginx Server Buildpack"
  homepage = "https://github.com/paketo-buildpacks/nginx"

[metadata]
  include_files = ["bin/build", "bin/detect", "bin/run", "bin/configure", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    nginx = "1.19.*"

  [[metadata.dependencies]]
    deprecation_date = "2021-05-01T00:00:00Z"
    id = "nginx"
    name = "Nginx Server"
    sha256 = "10435f5f0c512e0744e53dce7553f7b1ac7cd7377e244d2d7ce83ff251c9ec7c"
    source = "http://nginx.org/download/nginx-1.18.0.tar.gz"
    source_sha256 = "4c373e7ab5bf91d34a4f11a0c9496561061ba5eee6020db272a17a7228d35f99"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.18.0_linux_x64_cflinuxfs3_10435f5f.tgz"
    version = "1.18.0"

  [[metadata.dependencies]]
    deprecation_date = "2021-05-01T00:00:00Z"
    id = "nginx"
    name = "Nginx Server"
    sha256 = "5231999f03ea138a2c166a781f3b062de3d70f2860a9d6b505c24989ebccab6a"
    source = "http://nginx.org/download/nginx-1.19.2.tar.gz"
    source_sha256 = "7c1f7bb13e79433ee930c597d272a64bc6e30c356a48524f38fd34fa88d62473"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.19.2_linux_x64_cflinuxfs3_5231999f.tgz"
    version = "1.19.2"

  [[metadata.dependencies]]
    deprecation_date = "2021-05-01T00:00:00Z"
    id = "nginx"
    name = "Nginx Server"
    sha256 = "710546eaea6a7397b1cc00a57131b0af6576144ebcd73f993bb40ea062110c33"
    source = "http://nginx.org/download/nginx-1.19.3.tar.gz"
    source_sha256 = "91e5b74fa17879d2463294e93ad8f6ffc066696ae32ad0478ffe15ba0e9e8df0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.19.3_linux_x64_cflinuxfs3_710546ea.tgz"
    version = "1.19.3"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-05-01T00:00:00Z
    link = "https://nginx.org/"
    name = "nginx"
    version_line = "1.18.x"
  [metadata.version-lines]
    mainline = "1.19.*"
    stable = "1.18.*"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
