api = "0.4"

[buildpack]
  id = "paketo-buildpacks/nginx"
  name = "Paketo Nginx Server Buildpack"
  homepage = "https://github.com/paketo-buildpacks/nginx"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "bin/configure", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    nginx = "1.19.*"

  [[metadata.dependencies]]
    deprecation_date = "2021-05-01T00:00:00Z"
    id = "nginx"
    name = "Nginx Server"
    sha256 = "10435f5f0c512e0744e53dce7553f7b1ac7cd7377e244d2d7ce83ff251c9ec7c"
    source = "http://nginx.org/download/nginx-1.18.0.tar.gz"
    source_sha256 = "4c373e7ab5bf91d34a4f11a0c9496561061ba5eee6020db272a17a7228d35f99"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.18.0_linux_x64_cflinuxfs3_10435f5f.tgz"
    version = "1.18.0"

  [[metadata.dependencies]]
    deprecation_date = "2021-05-01T00:00:00Z"
    id = "nginx"
    name = "Nginx Server"
    sha256 = "4a2980eccb3b8e1f77ae1553cebd52f7bc0475814821a16ab7e832dbd1bcc81f"
    source = "http://nginx.org/download/nginx-1.19.9.tar.gz"
    source_sha256 = "2e35dff06a9826e8aca940e9e8be46b7e4b12c19a48d55bfc2dc28fc9cc7d841"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.19.9_linux_x64_cflinuxfs3_4a2980ec.tgz"
    version = "1.19.9"

  [[metadata.dependencies]]
    deprecation_date = "2021-05-01T00:00:00Z"
    id = "nginx"
    name = "Nginx Server"
    sha256 = "cc11525667ebbc126ea27930446489990ab59131612993b7cfb60ddac9dfc0a4"
    source = "http://nginx.org/download/nginx-1.19.10.tar.gz"
    source_sha256 = "e8d0290ff561986ad7cd6c33307e12e11b137186c4403a6a5ccdb4914c082d88"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.19.10_linux_x64_cflinuxfs3_cc115256.tgz"
    version = "1.19.10"

  [[metadata.dependencies]]
    id = "nginx"
    name = "Nginx Server"
    sha256 = "801bde5e490b3341e5780e77a0736e904e89dc9bf3000077b2ade4c3834d443b"
    source = "http://nginx.org/download/nginx-1.20.0.tar.gz"
    source_sha256 = "54ef91ec8ebcaa486c640c09c92d832eaeaff149b10ee52ef140f407b1b04d1c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.20.0_linux_x64_cflinuxfs3_801bde5e.tgz"
    version = "1.20.0"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-05-01T00:00:00Z
    link = "https://nginx.org/"
    name = "nginx"
    version_line = "1.18.x"
  [metadata.version-lines]
    mainline = "1.19.*"
    stable = "1.18.*"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
