api = "0.2"

[buildpack]
  id = "paketo-buildpacks/nginx"
  name = "Paketo Nginx Server Buildpack"
  homepage = "https://github.com/paketo-buildpacks/nginx"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "bin/configure", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    nginx = "1.19.*"

  [[metadata.dependencies]]
    deprecation_date = "2021-05-01T00:00:00Z"
    id = "nginx"
    name = "Nginx Server"
    sha256 = "10435f5f0c512e0744e53dce7553f7b1ac7cd7377e244d2d7ce83ff251c9ec7c"
    source = "http://nginx.org/download/nginx-1.18.0.tar.gz"
    source_sha256 = "4c373e7ab5bf91d34a4f11a0c9496561061ba5eee6020db272a17a7228d35f99"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.18.0_linux_x64_cflinuxfs3_10435f5f.tgz"
    version = "1.18.0"

  [[metadata.dependencies]]
    deprecation_date = "2021-05-01T00:00:00Z"
    id = "nginx"
    name = "Nginx Server"
    sha256 = "ebfbdde54ceba0a11584ff856a8d8a794b9a267cdeae1e4588cbe1060d354510"
    source = "http://nginx.org/download/nginx-1.19.7.tar.gz"
    source_sha256 = "7ae4dd020c41d3a5e1e6a8578fcc60e508e3e27e7668e845ddc87a05a775b50e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.19.7_linux_x64_cflinuxfs3_ebfbdde5.tgz"
    version = "1.19.7"

  [[metadata.dependencies]]
    deprecation_date = "2021-05-01T00:00:00Z"
    id = "nginx"
    name = "Nginx Server"
    sha256 = "0d7615018e2576324d9cf53ef47b25640bdf1febc6d4ceca8afc4ce8843f9979"
    source = "http://nginx.org/download/nginx-1.19.8.tar.gz"
    source_sha256 = "308919b1a1359315a8066578472f998f14cb32af8de605a3743acca834348b05"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.19.8_linux_x64_cflinuxfs3_0d761501.tgz"
    version = "1.19.8"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-05-01T00:00:00Z
    link = "https://nginx.org/"
    name = "nginx"
    version_line = "1.18.x"
  [metadata.version-lines]
    mainline = "1.19.*"
    stable = "1.18.*"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
