api = "0.2"

[buildpack]
  id = "paketo-buildpacks/nginx"
  name = "Nginx Server Buildpack"
  homepage = "https://github.com/paketo-buildpacks/nginx"

[metadata]
  include_files = ["bin/build", "bin/detect", "bin/run", "bin/configure", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    nginx = "1.17.*"

  [[metadata.dependencies]]
    deprecation_date = "2020-05-01T00:00:00Z"
    id = "nginx"
    name = "Nginx Server"
    sha256 = "c072d5dcb1f4efbd757d728dd2778261c070724e060bdeaca89cdfee9e15b0a9"
    source = "http://nginx.org/download/nginx-1.17.9.tar.gz"
    source_sha256 = "7dd65d405c753c41b7fdab9415cfb4bdbaf093ec6d9f7432072d52cb7bcbb689"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.17.9_linux_x64_cflinuxfs3_c072d5dc.tgz"
    version = "1.17.9"

  [[metadata.dependencies]]
    deprecation_date = "2020-05-01T00:00:00Z"
    id = "nginx"
    name = "Nginx Server"
    sha256 = "2fe87dae65967cfbbc570f986aa52fc574d6555c71799f2a781487d96c59d26d"
    source = "http://nginx.org/download/nginx-1.17.10.tar.gz"
    source_sha256 = "a9aa73f19c352a6b166d78e2a664bb3ef1295bbe6d3cc5aa7404bd4664ab4b83"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.17.10_linux_x64_cflinuxfs3_2fe87dae.tgz"
    version = "1.17.10"

  [[metadata.dependencies]]
    deprecation_date = "2021-05-01T00:00:00Z"
    id = "nginx"
    name = "Nginx Server"
    sha256 = "10435f5f0c512e0744e53dce7553f7b1ac7cd7377e244d2d7ce83ff251c9ec7c"
    source = "http://nginx.org/download/nginx-1.18.0.tar.gz"
    source_sha256 = "4c373e7ab5bf91d34a4f11a0c9496561061ba5eee6020db272a17a7228d35f99"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.18.0_linux_x64_cflinuxfs3_10435f5f.tgz"
    version = "1.18.0"

  [[metadata.dependencies]]
    deprecation_date = "2021-05-01T00:00:00Z"
    id = "nginx"
    name = "Nginx Server"
    sha256 = "3f26a5b7aad63203687c504f57846ee864512ef8ef7b340d8f03887516f1b1cd"
    source = "http://nginx.org/download/nginx-1.19.0.tar.gz"
    source_sha256 = "44a616171fcd7d7ad7c6af3e6f3ad0879b54db5a5d21be874cd458b5691e36c8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.19.0_linux_x64_cflinuxfs3_3f26a5b7.tgz"
    version = "1.19.0"

  [[metadata.dependencies]]
    deprecation_date = "2021-05-01T00:00:00Z"
    id = "nginx"
    name = "Nginx Server"
    sha256 = "b5af01b00ee2fd3da7c3f94de468f8480ba4d324757bc864ab07a04ae6dc990b"
    source = "http://nginx.org/download/nginx-1.19.1.tar.gz"
    source_sha256 = "a004776c64ed3c5c7bc9b6116ba99efab3265e6b81d49a57ca4471ff90655492"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.19.1_linux_x64_cflinuxfs3_b5af01b0.tgz"
    version = "1.19.1"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-05-01T00:00:00Z
    link = "https://nginx.org/"
    name = "nginx"
    version_line = "1.17.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-05-01T00:00:00Z
    link = "https://nginx.org/"
    name = "nginx"
    version_line = "1.18.x"
  [metadata.version-lines]
    mainline = "1.18.*"
    stable = "1.17.*"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
